# Generated by Django 5.2.5 on 2025-08-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('value', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('bad', 'bad'), ('medium', 'medium'), ('good', 'good')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
